mgs: Dev Profile Updated
environments:
  eureka-ip: localhost
  gateway-ip: localhost
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    #    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      show-sql: true
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: postgres
        id.new_generator_mappings: true
#        dialect: org.hibernate.dialect.Oracle12cDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
#    url: jdbc:oracle:thin:@//localhost:1521/
#    username: NGPIMS_LIVE
#    password: NGPIMS#$Bp123
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    username: NGPIMS_LIVE
#    password: NGPIMS#$Bp123

# Eureka Server
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${environments.eureka-ip}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${environments.eureka-ip}:8761/eureka/
# Key
config:
  oauth2:
    clientid: ibcsplanningidsdp
    clientSecret: planningIdsdpsha$@#929%
    privateKey: -----BEGIN RSA PRIVATE KEY-----MIIEpAIBAAKCAQEAqO6gisH+I7vONsPXyNDmncR2WdoiGWSLBzeNdbQa2bT7Pnnm11QlPngKAiRzL+u9NS0Hu4IU3HZEOOf+kjn8WZmGtjRgXF1ikp8oG6IR0fKPNbh6OoW+J0oKcp6HDot68s/HaucFLSLSlOy4T39XblGv2uaaienSaUzWviwcroZUlfEsZFE9BW4CYGxWJ3cUqmzeIl2Cmyq71QXWndVNC9iBwSmd7AiRhnMyATGbO8sAwh3cXkekCFxrke6WtOo0vkpzeL7kDMgY8msypdtTgPhUfwRGVhF6V6yN6VgfaJqzVlQO+Ned5Gg0GQKSjMm69ycS9llrD5Hvkkq/z1cANwIDAQABAoIBAFrDErhab/us7KdZ43a+XhlHs7qkywtPjK7M9xDVOlPbu90eS5tHV1dP0TjDcqu9gYOvdOcWhbTJSfA1HP5dbyqIpOsCCv+1IL/cCQWHtwFQzAa13d3Re4/KZQCeEbwLznvkjKTwCETu36sp4AC+TzAzbUM0ALW2TdlLcljshGBzZjj6ABPe8G46yLnXQ8pCzMBX1MwMYzeOLZdkD/2mkRGu9dt4KJFZsdCqYp/BZXxTpRf7l0RhRrl1pZHFjJN52hsPJIDmifuIVlOblSS643qmvON6v2FLFdC3gmhsYSIvme9Jk2p30FdrTNoJ8KT2wrU4AjKQXyYeRFJ+QR0p6jECgYEA1Sb5TcHg8oMYqQFxtxjZdKUJ81krmmfLDZ6OI9W20xwWg1Juf3/m+FCVGUeGLmw63VN1cFDx8yfAQK5YMFkySZtkirCd2uIVO9aoD9w2eLeLocUl0IBJuPK+drWeaZwZjwp4fbmf4BU77DKUS3TmQHRY1ZAX1jFHER9LTbFBUvkCgYEAyuQK8msaY3AzBo5U30XwiYotUX0/FiDpQ/rhpd8YzrGWgV7NHsZigCk8wXxuMQchU4snMff4XdnHxogpIS/eARJqBh//3I/hGPlJUjt95eRjnuXfV05fOFVEYfyHmR68OHrbgujHEpTB6YFdnbqP5Hw6WTZIFVknIabakqgziK8CgYEApz6jUk2TkPUn/kOx0/ZdeVadjiEjQ025VwBXiup/PvnE+FlPdh8HPUMNGf6y2+3z6gE4Hl6E2UMRaC7j51u1R2fz5ZZa5YmLG55706X335Q0rUOhPg3KyqE8rKwolbjznPacQBnLxekjUVsGXIZmu6AOq9MZwOh9WIPzdAxmsxECgYBL3Cgbq+AZ/gGWGfGx6byeMIPxTBsicvvE5zEni9sCrXPQu1mGgDakJMcKsTOiMUBMtGLbVBQRQzRnDtISDou7at8pmx1XopRPeiXoEUZphpOY/eocArmnnnoLCRjKL6vAkm8w60hDsksuu6f9KZxTmf9XC+y3zrXK51AiNbHPEQKBgQDM12Ur5FiKuCXR+7RypK8ssv2sz8YTPrcEsZYvh6USg8sxIOv9NXb7ABMGJ507xRXbizsOsMLbbD7fukNHd4ha1sJTJcr2lsD/qpJn3fHkPoKEqxvBIeup94arlJUJxorNDpNgXooFooA0hp1jtuLRe3PtoBh461/YLTzplxU63g==-----END RSA PRIVATE KEY-----
    publicKey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqO6gisH+I7vONsPXyNDmncR2WdoiGWSLBzeNdbQa2bT7Pnnm11QlPngKAiRzL+u9NS0Hu4IU3HZEOOf+kjn8WZmGtjRgXF1ikp8oG6IR0fKPNbh6OoW+J0oKcp6HDot68s/HaucFLSLSlOy4T39XblGv2uaaienSaUzWviwcroZUlfEsZFE9BW4CYGxWJ3cUqmzeIl2Cmyq71QXWndVNC9iBwSmd7AiRhnMyATGbO8sAwh3cXkekCFxrke6WtOo0vkpzeL7kDMgY8msypdtTgPhUfwRGVhF6V6yN6VgfaJqzVlQO+Ned5Gg0GQKSjMm69ycS9llrD5Hvkkq/z1cANwIDAQAB-----END PUBLIC KEY-----
